spring:
  application:
     name: GATEWAY-SERVICE
  cloud:
     gateway:
       routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:  
             - Path=/booking/** 
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:  
             - Path=/payment/** 
        - id: enrollment-service
          uri: lb://ENROLLMENT-SERVICE
          predicates:  
             - Path=/profile/**
        - id: mail-service
          uri: lb://MAIL-SERVICE
          predicates:  
             - Path=/GetOrderInfoMail/** 
server:
  port: 9079
eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
      defaultZone: http://localhost:8761/eureka/  

    